[project]
name = "rl-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "box2d>=2.3.10",
    "gymnasium>=1.2.1",
    "pygame>=2.6.1",
    "torch>=2.8.0",
]
